table! {
    use diesel::sql_types::*;
	markets (
		id, 
		description, 
		extra_info, 
		creator, 
		creation_date, 
		end_date_time, 
		outcomes, 
		outcome_tags, 
		categories, 
		winning_outcome, 
		resoluted, 
		resolute_bond, 
		filled_volume, 
		disputed, 
		finalized, 
		creator_fee_percentage, 
		resolution_fee_percentage, 
		affiliate_fee_percentage, 
		api_source, 
		validity_bond_claimed
	) {
		id -> Numeric,
		description -> Text,
		extra_info -> Text,
		creator -> Text,
		creation_date -> Timestamp,
		end_date_time -> Timestamp,
		outcomes -> SmallInt,
		outcome_tags -> Array<Text>,
		categories -> Array<Text>,
		winning_outcome -> SmallInt,
		resoluted -> Bool,
		resolute_bond -> Numeric,
		filled_volume -> Numeric,
		disputed -> Bool,
		finalized -> Bool,
		creator_fee_percentage-> SmallInt,
		resolution_fee_percentage-> SmallInt,
		affiliate_fee_percentage-> SmallInt,
		api_source-> Text,
		validity_bond_claimed -> Bool,
    }
}